change: app title
codeuniversity/code-idp pull request #4
Opened 2024-02-29 17:06 UTC by Till1983

I changed the app title in app-config.yaml to "CODE Internal Developer Platform".

2024-03-12 13:30 UTC, Till1983 commented
@MennaTullahTaha I completely forgot to tag you here. I hope it's not too late for a review.

2024-03-18 11:21 UTC, MennaTullahTaha requested changes

2024-03-18 11:21 UTC, MennaTullahTaha commented on app-config.yaml
@juliusdw @DrAdamRoe 
As far as I understand the e2e test expects Scaffold Backstage App to pass the tests, wouldn't that break the e2e? someone will need to make a change I assume.

2024-04-09 18:17 UTC, juliusdw commented on app-config.yaml
yes, the e2e test need to be changed as follows:
change this line in `app/e2e-tests/app.test.ts`
from
`await expect(page.getByText('Scaffolded Backstage App')).toBeVisible();`
to
`await expect(page.getByText('CODE Internal Developer Platform')).toBeVisible();`

2024-04-14 13:42 UTC, Till1983 commented on app-config.yaml
@MennaTullahTaha @DrAdamRoe  
I changed the e2e test in `packages/app/e2e-tests/app.test.ts`, just like @juliusdw pointed out. The title is now consistent with the change to the title that I made in `app-config.yaml`. I'm sorry for the long delay!

2024-04-30 15:38 UTC, closed without merging